// Constants.js
export const ROUTES = {
  LOGIN: 'Login',
  SIGNUP: 'Signup',
  RECOVERY_PASSWORD: 'Recovery password',
  OTP_SCREEN: 'Otp screen',
  ITEM_SCREEN: 'Item Screen',
  PROFILE: 'Profile',
  READING: 'Reading',
  HOME: 'Home',
  HOME_TAB: 'Home Tab',
  HOME_DRAWER: 'Home Drawer',
  DASHBOARD: 'Dashboard',
  PROFILE_SETTING: 'Profile',
  WELCOME: 'Welcome',
  FAQ: 'FAQ',
  PORTAL: 'Referral Portal',
  PRICING: 'Pricing',
  OFFLINE: 'Offline',
  NOTIFICATIONS: 'Notifications',
  PRODUCT_DETAILS: 'Product Details',
  CART: 'Cart',
  TRACKING: 'Tracking',
  HISTORY: 'History',
  RESET_PASSWORD: 'Reset password',
  SEARCH: 'Search',
  RESET_HANDLE: 'Reset handle',
};
